### ISSUE TITLE
Deliberate disconnection - skipping reconnect attempts

### ISSUE THREAD

**Issue by Vincent-CDeng** [pusher/pusher-websocket-swift#176]
OCAuthMethod *authMethod = [[OCAuthMethod alloc] initWithAuthEndpoint:@"endpoint"];
                                
    OCPusherHost *host = [[OCPusherHost alloc]initWithHost:@"host"];
    PusherClientOptions *options = [[PusherClientOptions alloc]
                                    initWithOcAuthMethod:authMethod
                                    attemptToReturnJSONObject:YES
                                    autoReconnect:YES
                                    ocHost:host
                                    port:@8180
                                    encrypted:NO];
    _pusher = [[Pusher alloc] initWithAppKey:@"secrete" options:options];
    
//    _pusher = [[Pusher alloc] initWithKey:@"232423"];
    [_pusher connect];
    _pusher.connection.delegate = self;
    
    PusherChannel *myChannel = [_pusher subscribeWithChannelName:@"channel"];
    [myChannel bindWithEventName:@"event" callback: ^void (NSDictionary *data) {
        NSLog(@"Subscribed!");
//        NSLog(@"I can now access myId: %@", myChannel.myId);
//        NSLog(@"And here are my channel members: %@", myChannel.members);
    }];

use this code to  can successfully establish connect ,but after about 60 seconds ,it will be disconnected and this is its log :message:[PUSHER DEBUG] Deliberate disconnection - skipping reconnect attempts

**Comment by hamchapman** [comment]
Just to check, you aren't calling `disconnect` anywhere in your code?

I have noticed that recent versions of Starscream (the underlying websocket library that is used in this library) seem to return an error with code `1` but the `CloseCode.normal.rawValue`, which is what we check for in this library, is now defined as `1000`. So it could be that some error codes are being reported or checked incorrectly.

Does this happen every time for you or is it intermittent?

**Comment by Vincent-CDeng** [comment]
No, double check my code ,i didn't call disconnect.
and this happen every time .
is there any chance i can fix it ?

**Comment by hamchapman** [comment]
The code you pasted looks a bit strange. For example, it looks like you're potentially using your app ID or secret instead of your app key when you do:

```
_pusher = [[Pusher alloc] initWithAppKey:@"secrete" options:options];
```

That should be your app's key that you pass in then.

You also shouldn't need to be providing a `host` value in the `options`, nor a `port`. That's config that's specifying where the websocket connection should be attempted. But you don't want that. It might be easier to help debug if you get in contact with support as I don't think this is a library related issue. You can contact support here: https://dashboard.pusher.com/technical-help

I'll keep this issue open for a while in case you have more comments / questions though 👍

**Comment by Vincent-CDeng** [comment]
i did what exactly  the tutorial tell me to do ,but i can't manage to establish connection,this is the only way i can establish connecttion ,i'll provide you more information next monday .thanks for  keep this open

**Comment by Vincent-CDeng** [comment]
OCAuthMethod *authMethod = [[OCAuthMethod alloc] initWithAuthEndpoint:@"http://92.168.1.205:8180"];
                                
    OCPusherHost *host = [[OCPusherHost alloc]initWithHost:@"192.168.1.205"];
    PusherClientOptions *options = [[PusherClientOptions alloc]
                                    initWithOcAuthMethod:authMethod
                                    attemptToReturnJSONObject:YES
                                    autoReconnect:YES
                                    ocHost:host
                                    port:@8180
                                    encrypted:NO];
    _pusher = [[Pusher alloc] initWithAppKey:@"47e*****5" options:options];
    _pusher.connection.OCReconnectAttemptsMax = @(100);
    
//    _pusher = [[Pusher alloc] initWithKey:@"470875"];
    [_pusher connect];
    _pusher.connection.delegate = self;
    
    PusherChannel *myChannel = [_pusher subscribeWithChannelName:@"market-global"];
    [myChannel bindWithEventName:@"tickers" callback: ^void (NSDictionary *data) {
        NSLog(@"Subscribed!");
//        NSLog(@"I can now access myId: %@", myChannel.myId);
//        NSLog(@"And here are my channel members: %@", myChannel.members);
    }];

how about this code ,and if  i pass nil ni in  host field in options ,app would crash

**Comment by vostricov** [comment]
I'm having the same issue: "Deliberate disconnection - skipping reconnect attempts". In my case it is caused by .endEncountered event. The Starscream throws nil instead of error. What could be a reason?

**Comment by hamchapman** [comment]
@vostricov I encourage you try the `cleanup-crash-fix` branch (associated PR here: https://github.com/pusher/pusher-websocket-swift/pull/178)

This should have fixed this problem. 

Let me know if you're able to and what results you see 👍  I'm hoping to merge that PR and release 6.0.0 on Monday if all goes well.

**Comment by vostricov** [comment]
@hamchapman I added the following line into my Podfile:
pod 'PusherSwift', :git => 'https://github.com/pusher/pusher-websocket-swift.git', :branch => 'cleanup-crash-fix'
but pod install fails to find specs for Reachability (~> 4.1.0). I updated the source repos but it didn't help.

**Comment by hamchapman** [comment]
Ah that might need to be “Reachability.swift”

Give me a moment and I’ll push to the branch

**Comment by hamchapman** [comment]
@vostricov I've just pushed to the branch with a fix for the podspec

**Comment by vostricov** [comment]
@hamchapman You might need to update all 'import Starscream' to 'import StarscreamFork'. After that I could successfully compile the fixed pod. 
Now after receiving "[PUSHER DEBUG] Websocket is disconnected but no error received" the attemptReconnect() returns immediately because connectionState is still .connected. Should it be set to other value before attempting to reconnect?

**Comment by hamchapman** [comment]
Thanks for the `StarscreamFork` spot - I'll take a look into that now.

And the `connectionState` might need to be set explicitly as well - I'll check that now too 👍

**Comment by hamchapman** [comment]
Okay I've pushed to the `cleanup-crash-fix` branch to fix the `StarscreamFork` issue.

The disconnection one I was unable to reproduce.

If you clone down this repo, checkout the `cleanup-crash-fix` branch, add your Pusher app key and auth endpoint info to the iOS Example app and then try disconnecting and connecting again using the example app, does that work for you? Thanks!

**Comment by vostricov** [comment]
@hamchapman thanks for that. I confirm that the `StarscreamFork` issue was resolved. But I still experience problem with disconnection flow. I reproduced it on iOS Example app as well. The scenario is as follows:

1. I successfully connect to my channel
2. At some point (reason doesn't matter) the Starscream calls this line:
`s.delegate?.websocketDidDisconnect(socket: s, error: error)`
3. The delegate's connection state is still `.connected`. It will be reset to .disconnected only if options.autoReconnect is false or if maximum attempts num is reached.  Otherwise it will keep the `.connected` state
4. The delegate (PusherConnection) calls attemptReconnect which returns immediately because of this condition:
```
guard connectionState != .connected else {
            return
 }
```
5. As result the reconnect will never happen.

**Comment by hamchapman** [comment]
Ah okay, so you're talking about a scenario where it _isn't_ a deliberate disconnect?

I think you're right that there needs to be a state change to `.disconnected` even if `autoReconnect` is set to false. I'll take a look at that tomorrow. Thanks for the detailed steps again!

**Comment by vostricov** [comment]
Yes, I'm talking about _non_-deliberate disconnect. In this case the reconnection will never happen even if the `autoReconnect` is `true` OR `connect()` method is called explicitly. Probably it had to be raised as a separate issue.

**Comment by Vincent-CDeng** [comment]
Unable to find a specification for `StarscreamFork (~> 3.0.6)` depended upon by `PusherSwift`

**Comment by vostricov** [comment]
@hamchapman Works perfectly well now! 👍 Many thanks for your quick responses and all help! Please let me know when you are going to release 6.0.0 version with this fix

**Comment by hamchapman** [comment]
Great! Thanks for letting me know.

I'm hoping that some of the other people affected by fixes in the upcoming release get a chance to try it out before I release it, but I'm pretty confident about it now, so I expect I'll push out a 6.0.0 release tomorrow or Thursday 👍

**Comment by vostricov** [comment]
@hamchapman is there any update on release date?

**Comment by hamchapman** [comment]
It’ll likely be on Wednesday now. Sorry about the delay. I didn’t get a chance to release before the holidays here and then Swift 4.1 was released as well, which I need to do a few checks for.
